### PR TITLE
Fix loop overruns in chassis code

### LINKED ISSUE #311: Investigate HolonomicDrive Loop overruns

### PR DESCRIPTION
**Pull request by witcpalek**
closes #311

### CODE REVIEW

File: src/main/cpp/chassis/SwerveChassis.cpp [hunk 1]
```diff
@@ -156,11 +161,17 @@ void SwerveChassis::ZeroAlignSwerveModules()
 /// @brief Drive the chassis
 void SwerveChassis::Drive(ChassisMovement &moveInfo)
 {
+    auto timer(std::make_unique<frc::Timer>());
```
Comment (Tan560) [inline src/main/cpp/chassis/SwerveChassis.cpp:164]: Did you want to keep the logging in?

File: src/main/cpp/chassis/SwerveChassis.cpp [hunk 2]
```diff
@@ -45,6 +45,9 @@
 
 // Third Party Includes
 #include "pugixml/pugixml.hpp"
+#include <ctre/phoenix6/StatusSignal.hpp>
+
```
Comment (Tan560) [inline src/main/cpp/chassis/SwerveChassis.cpp:49]: Did you mean to keep the timer and logging in?

**Review by Tan560 — CHANGES_REQUESTED** [review]

File: src/main/cpp/chassis/SwerveChassis.cpp (hunk 1 above)
Comment (witcpalek) [reply src/main/cpp/chassis/SwerveChassis.cpp:164]: fixed

File: src/main/cpp/chassis/SwerveChassis.cpp (hunk 2 above)
Comment (witcpalek) [reply src/main/cpp/chassis/SwerveChassis.cpp:49]: removed
